/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IExchangeWrapper,
  IExchangeWrapperInterface,
} from "../IExchangeWrapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ERC20",
        name: "inputToken",
        type: "address",
      },
      {
        internalType: "contract ERC20",
        name: "outputToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "inputTokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOutputTokenAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "transformations",
        type: "bytes",
      },
    ],
    name: "transformERC20",
    outputs: [
      {
        internalType: "uint256",
        name: "outputTokenAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IExchangeWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): IExchangeWrapperInterface {
    return new utils.Interface(_abi) as IExchangeWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExchangeWrapper {
    return new Contract(address, _abi, signerOrProvider) as IExchangeWrapper;
  }
}
