/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IStarkwareContract,
  IStarkwareContractInterface,
} from "../IStarkwareContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "starkKey",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "assetType",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "quantizedAmount",
        type: "uint256",
      },
    ],
    name: "depositERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ethKey",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "starkKey",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "assetType",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "quantizedAmount",
        type: "uint256",
      },
    ],
    name: "registerAndDepositERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStarkwareContract__factory {
  static readonly abi = _abi;
  static createInterface(): IStarkwareContractInterface {
    return new utils.Interface(_abi) as IStarkwareContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStarkwareContract {
    return new Contract(address, _abi, signerOrProvider) as IStarkwareContract;
  }
}
